<?php

return [
    'only' => [
        'home',
        'marketplace.index',
        'marketplace.show',
        'marketplace.products.show',
        'orders.index',
        'profile.edit',
        'logout',
        'orders.show',
        'parents',
        'info',
        'faq',
        'password.request',
        'password.store',
        'password.confirm',
        'password.email',
        'password.update',
        'verification.send',
        'register',
        'checkout.index',
        'login',
        'orders.messages.show',
        'orders.messages.store',
        'search',
        'cart.index',
        'cart.store',
        'cart.destroy',
        'profile.update',
        'checkout.store'
        //        'home',
        //
        //        'marketplace.index',
        //        'marketplace.products',
        //        'marketplace.checkout',
        //        //
        //        //        'dashboard',
        //        //
        //        'profile.edit',
        //        //        'profile.update',
        //        //        'profile.destroy',
        //        //        'password.edit',
        //        //        'password.update',
        //        //        'appearance',
        //        //
        //        'register',
        //        'login',
        //        'password.request',
        //        'password.email',
        //        'password.reset',
        //        'password.store',
        //        'verification.notice',
        //        'verification.verify',
        //        'verification.send',
        //        'password.confirm',
        //        'logout',
    ],
//    'except' => ['filament.*', 'livewire.*'],
];
