apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dzikshop-bot

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - app/deployment.yaml
  - app/pvc.yaml

configMapGenerator:
  - name: bot-config
    files:
      - secrets/config.js

secretGenerator:
  - name: dzikshop-docker-registry
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=secrets/dockerconfig.json

images:
  - name: dzikshop-bot
    newName: registry.gitlab.com/zergly/projects/dzikshop-pl/discordbot
    newTag: latest